CleanArch_Project/RazorSample/Pages/Account/Info/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;
using ApplicationCore.Services;
using ApplicationCore.DTOs;
using Web.Services;
using Web.ViewModels;
using Microsoft.AspNetCore.Http;

namespace Web.Pages.Account.Info
{
    public class DetailsModel : PageModel
    {
        private readonly UserVmService _service;
        [BindProperty(SupportsGet = true)]
        public string CurrentFilterProduct { get; set; }

        public DetailsModel(UserVmService service)
        {
            _service = service;
        }

        public UserDto User { get; set; }


        public UserVm userVm { get; set; }
        public IActionResult OnGet(int id)
        {

            //neu da dang nhap
            if(HttpContext.Session.GetString("username") != null)
            {

              
                    userVm = _service.GetUserViewModel(id);
              
                    
                
               
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }


            
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_products
{
    public class DetailsModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public DetailsModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        public Product Product { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product
                .Include(p => p.ProductProvider).FirstOrDefaultAsync(m => m.ProductId == id);

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_users/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_users
{
    public class DetailsModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public DetailsModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        public User User { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.User
                .Include(u => u.UserCustomer)
                .Include(u => u.UserPermission).FirstOrDefaultAsync(m => m.UserId == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

CleanArch_Project/RazorSample/Pages/Basket/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.DTOs;
using ApplicationCore.Entities;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages.Basket
{
    public class ViewModel : PageModel
    {
        private readonly ProductService _service;
        private readonly OrderService _service1;
        [BindProperty(SupportsGet = true)]
        public string CurrentFilterProduct { get; set; }
        public ViewModel(ProductService service, OrderService service1)
        {
            _service = service;
            _service1 = service1;
        }

        [BindProperty]
        public OrderDto Order { get; set; }
        [BindProperty]
        public OrderDetailDto OrderDetail { get; set; }
        [BindProperty]
        public List<Item> cart { get; set; }

        public List<ProductDto> Products { get; set; }
        public double Total { get; set; }

        [BindProperty(SupportsGet = true)]
        public string message { get; set; }

        public IActionResult OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart != null)
            {
                Total = cart.Sum(i => i.Product.ProductPrice * i.Quantity);
                return Page();
            }
            else
            {
                Total = 0;
                return Page();
            }

        }

        public IActionResult OnGetBuyNow(int id)
        {
            //lay list<Product>

            Products = _service.GetListProducts().ToList<ProductDto>();



            //lay session list<Item>
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item
                {
                    Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else    //neu da ton tai item do thi chi can them 1 so luong
            {


                int index = Exists(cart, id);
                if (index == -1)  //neu chua co id trong cart thi them moi
                {
                    cart.Add(new Item
                    {
                        Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                        Quantity = 1
                    });
                }
                else   //ton tai thi tang so luong thoi
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("/Basket/View");
        }

        // xoa item trong cart

        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        // update quantity trong session
        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        //kiem tra id san pham da ton tai trong cart chua
        //neu ton tai thi tra ve id
        //neu khong thi tra ve -1

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }


        //thanhtoan
        public IActionResult OnPostThanhToan()
        {

            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (HttpContext.Session.GetString("username") == null)
            {
                message = "Ban chua dang nhap";
            }
            else
            {
                _service1.AddOrder(HttpContext.Session.GetString("username"), Order, cart, OrderDetail);

                //xoa session
                HttpContext.Session.Remove("cart");


            }

                return Page();
            
        }

    }
}

CleanArch_Project/RazorSample/Pages/Products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using ApplicationCore.Services;
using ApplicationCore.DTOs;
using Web.Services;
using Web.ViewModels;

namespace Web.Pages.Products
{
    public class DetailsModel : PageModel
    {
       
            private readonly ProductService _service;

            private readonly ProductListVmService _ProductService;
        

        public DetailsModel(ProductService service, ProductListVmService ProductService)
            {
                _service = service;
                _ProductService = ProductService;
        }
            [BindProperty(SupportsGet = true)]
            public string CurrentFilterProduct { get; set; }
            public List<Item> cart { get; set; }
        
            public ProductDto Product { get; set; }
            public int id_product { get; set; }
            
             public ProductListVm ProductIndexVM { get; set; }

            public IActionResult OnGet(int id,string typename,int pageIndex=1)
            {
                
                cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
                
                id_product = id;

                 ProductIndexVM = _ProductService.GetProductIndexViewModel(CurrentFilterProduct, typename, pageIndex);

                Product = _service.GetProduct(id);

                if (Product == null)
                {
                    return NotFound();
                }
                return Page();
            }
        }
}

CleanArch_Project/RazorSample/Pages/Products/Index.cshtml.cs
using ApplicationCore.Entities;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Collections.Generic;
using Web.Services;
using Web.ViewModels;

namespace Web.Pages.Products
{
    public class IndexModel : PageModel
    {
        private readonly ProductListVmService _ProductService;
        public IndexModel(ProductListVmService ProductService)
        {
            _ProductService = ProductService;
        }

        [BindProperty(SupportsGet = true)]
        public string CurrentFilterProduct { get; set; }

      

        [BindProperty(SupportsGet = true)]
        public string typename { get; set; }

        [BindProperty(SupportsGet = true)]
        public string sort{ get; set; }
        public List<Item> cart { get; set; }
        
        public ProductListVm ProductIndexVM { get; set; }
        public void OnGet(int pageIndex=1)
        {

           
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if(sort == "giam")
            {
              
                ProductIndexVM = _ProductService.GetProductPriceDecrease(CurrentFilterProduct, typename, pageIndex);

            }
            else
            {
                ProductIndexVM = _ProductService.GetProductIndexViewModel(CurrentFilterProduct, typename, pageIndex);
            }

          


        }
        



    }
}

CleanArch_Project/RazorSample/Pages/Products/Details.cshtml
@page
@model Web.Pages.Products.DetailsModel

@{
    ViewData["Title"] = "Details";
}

@section icon{
    <img src="/../images/logo1.png">
}

@section headers{


    @if (@HttpContext.Session.GetString("username") != null)
    {

        <li>
            Hello <a asp-page="/users/details" asp-route-id="@HttpContext.Session.GetString("userid")">@HttpContext.Session.GetString("username")</a>
        </li>
        <li>
            <form method="post">
                <input asp-page="/Account/Logout/DangXuat" type="submit" value="Log out" />
            </form>
        </li>

    }
    else    //chua dang nhap
    {

        <li>
            <a asp-page="/Account/Login/DangNhap"><i class="fa fa-unlock"></i> Đăng nhập</a>
        </li>
        <li>
            <a asp-page="/Account/Register/DangKy"><i class="fa fa-share-square-o"></i> Đăng ký</a>
        </li>
    }

}
@section search{
    <form method="get" class="form-inline">
        <div class="form-group">
            <input type="text" asp-for="CurrentFilterProduct" placeholder="Keyword" class="form-control">
            <button asp-page="/Products/index" value="Search" type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
        </div>
    </form>
}
@section slcart{

    @if (Model.cart == null)
    {
        <i>0 </i>
    }
    else
    {
        var soluong = 0;
        @foreach (var item in Model.cart)
        {
            soluong++;

        }
        <i>@soluong </i>

    }
}
<div class="col-md-3  fixside">
    <div class="box-left box-menu">
        <h3 class="box-title"><i class="fa fa-list"></i>  Danh mục</h3>
        <ul>
            @foreach (var item in Model.ProductIndexVM.typename)
            {

                <li>
                    <a href="http://localhost:25197/Products?typename=@item">@item<span class="badge pull-right"></span></a>
                </li>


            }

        </ul>
    </div>
</div>
<div class="col-md-9 bor">
    <div>
        <section class="box-main1">
            <div class="col-md-6 text-center">
                <img src="/../images/@Html.DisplayFor(model => model.Product.ProductImage)" class="img-responsive bor" id="imgmain" width="100%" height="370" data-zoom-image="images/16-270x270.png">
            </div>
            <div class="col-md-6 bor" style="margin-top: 20px;padding: 30px;">
                <ul id="right">
                    <li><h3> @Html.DisplayFor(model => model.Product.ProductName) </h3></li>
                    <li><p><b class="price">@Html.DisplayFor(model => model.Product.ProductPrice) đ</b></li>

                    <a asp-page="/Basket/View" asp-page-handler="buynow"
                       asp-route-id=@Model.id_product><i class="fa fa-shopping-basket"></i>Add To Cart</a>

                    <li>Còn lại:@Html.DisplayFor(model => model.Product.ProductQuantity)</li>


                </ul>
            </div>

        </section>
        <div class="col-md-12" id="tabdetail">
            <div class="row">
                <div class="tab-content">
                    <div>
                        <h3> Thông tin khác </h3>
                        <p>@Html.DisplayFor(model => model.Product.ProductDescription)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

CleanArch_Project/RazorSample/Pages/Products/Index.cshtml
@page

@model IndexModel
@{
    ViewData["Title"] = "Product";
}
<!--render sections-->

@section icon{
    <img src="/../images/logo1.png">
}

@section headers{


    @if (@HttpContext.Session.GetString("username") != null)
    {

        <li>
            Hello <a asp-page="/Account/info/details" asp-route-id="@HttpContext.Session.GetString("userid")">@HttpContext.Session.GetString("username")</a>
        </li>
        <li>
            <form method="post">
                <input asp-page="/Account/Logout/DangXuat" type="submit" value="Log out" />
            </form>
        </li>

    }
    else    //chua dang nhap
    {

        <li>
            <a asp-page="/Account/Login/DangNhap"><i class="fa fa-unlock"></i> Đăng nhập</a>
        </li>
        <li>
            <a asp-page="/Account/Register/DangKy"><i class="fa fa-share-square-o"></i> Đăng ký</a>
        </li>
    }

}

@section search{
    <form method="get" class="form-inline">
        <div class="form-group">
            <input type="text" asp-for="CurrentFilterProduct" placeholder="Keyword" class="form-control">
            <button asp-page="/Products/index" value="Search" type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
        </div>
    </form>
}
@section slcart{

    @if (Model.cart == null)
    {
        <i>0 </i>
    }
    else
    {
        var soluong = 0;
        @foreach (var item in Model.cart)
        {
            soluong++;

        }
        <i>@soluong </i>

    }
}
<style>



    .card {
        box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2);
        width: 200px;
        margin: auto;
        text-align: center;
        margin-top: 15px;
        font-family: arial;
        float: left;
        margin-left: 15px;
    }

    .img_frame {
        width: 200px;
        height: 250px;
        float: left;
        overflow: hidden;
        position: relative;
    }

    .blank_img {
        width: 200px;
        height: 250px;
        background-color: black;
        float: left;
    }

    .price {
        color: grey;
        font-size: 22px;
    }

    .img_frame img {
        transition: .3s ease-in;
    }

    .img_frame:hover img {
        transform: scale(1.3);
    }

    .card button {
        border: none;
        outline: 0;
        padding: 12px;
        color: white;
        background-color: #000;
        text-align: center;
        cursor: pointer;
        width: 100%;
        font-size: 18px;
    }

        .card button:hover {
            opacity: 0.7;
        }

    .container1 {
        clear: both;
    }
</style>

<div class="col-md-3  fixside">
    <div class="box-left box-menu">
        <h3 class="box-title"><i class="fa fa-list"></i>  Danh mục</h3>
        <ul>
            @foreach (var item in Model.ProductIndexVM.typename)
            {

                <li>
                    <a href="http://localhost:25197/Products?typename=@item">@item<span class="badge pull-right"></span></a>
                </li>


            }

        </ul>
    </div>
</div>
<div class="col-md-9 bor">
    <div>
        <form method="get">
            <p>
                <select asp-for="typename" asp-items="Model.ProductIndexVM.Genres">
                    <option value="">All</option>
                </select>
                Find by name: <input type="text" asp-for="CurrentFilterProduct" />
                <input type="submit" />
                <a asp-page="./index" asp-route-sort="giam"></a>
            </p>
        </form>

        <form method="post">
            <div class="text-center">
                <section class="box-main1">
                    <div class="showitem">
                        @foreach (var Product in Model.ProductIndexVM.Products)
                        {
                            <div class="col-md-3  item-product bor">
                                <a asp-page="./Details" asp-route-id="@Product.ProductId">
                                    <img src="/images/@Product.ProductImage" class="" width="100%" height="180">
                                </a>
                                <div class="info-item">
                                    <a class="cutboss" asp-page="./Details" asp-route-id="@Product.ProductId">
                                        <div class="cutboss">@Product.ProductName</div>

                                    </a>
                                    <p><b class="price">@Product.ProductPrice đ</b></p>
                                </div>
                                <a asp-page="/Basket/View" asp-page-handler="buynow"
                                   asp-route-id=@Product.ProductId><i class="fa fa-shopping-basket fa-3x"></i></a>

                            </div>
                        }
                    </div>
                </section>
            </div>
            <!--
            SIMPLE CARD PRODUCT

                        <td>
                            <button type="submit" asp-page-handler="Delete" asp-route-id="Product.ProductId">Delete</button>
                            <a asp-page="/Movies/Edit" asp-route-id="Product.ProductId">Edit</a>
                        </td>
            -->



        </form>
    </div>


    <div>
        @{
            var preDisabled = !Model.ProductIndexVM.Products.HasPrevious ? "disabled" : "";
            var nextDisabled = !Model.ProductIndexVM.Products.HasNext ? "disabled" : "";
        }
        <div class="container1">

            <a asp-page="Index"
               asp-route-currentFilterproduct="@Model.CurrentFilterProduct"
               asp-route-typename="@Model.typename"
               asp-route-sort="@Model.sort"
               asp-route-pageIndex="@(Model.ProductIndexVM.Products.PageIndex - 1)"
               class="btn btn-default @preDisabled">Previous</a>

            <a asp-page="Index"
               asp-route-currentFilterproduct="@Model.CurrentFilterProduct"
               asp-route-typename="@Model.typename"
               asp-route-sort="@Model.sort"
               asp-route-pageIndex="@(Model.ProductIndexVM.Products.PageIndex + 1)"
               class="btn btn-default @nextDisabled">Next</a>
        </div>
    </div>
</div>