CleanArch_Project/RazorSample/Pages/Basket/View.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.DTOs;
using ApplicationCore.Entities;
using ApplicationCore.Services;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Web.Pages.Basket
{
    public class ViewModel : PageModel
    {
        private readonly ProductService _service;
        private readonly OrderService _service1;
        [BindProperty(SupportsGet = true)]
        public string CurrentFilterProduct { get; set; }
        public ViewModel(ProductService service, OrderService service1)
        {
            _service = service;
            _service1 = service1;
        }

        [BindProperty]
        public OrderDto Order { get; set; }
        [BindProperty]
        public OrderDetailDto OrderDetail { get; set; }
        [BindProperty]
        public List<Item> cart { get; set; }

        public List<ProductDto> Products { get; set; }
        public double Total { get; set; }

        [BindProperty(SupportsGet = true)]
        public string message { get; set; }

        public IActionResult OnGet()
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart != null)
            {
                Total = cart.Sum(i => i.Product.ProductPrice * i.Quantity);
                return Page();
            }
            else
            {
                Total = 0;
                return Page();
            }

        }

        public IActionResult OnGetBuyNow(int id)
        {
            //lay list<Product>

            Products = _service.GetListProducts().ToList<ProductDto>();



            //lay session list<Item>
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (cart == null)
            {
                cart = new List<Item>();
                cart.Add(new Item
                {
                    Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                    Quantity = 1
                });
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            else    //neu da ton tai item do thi chi can them 1 so luong
            {


                int index = Exists(cart, id);
                if (index == -1)  //neu chua co id trong cart thi them moi
                {
                    cart.Add(new Item
                    {
                        Product = Products.Where(p => p.ProductId == id).FirstOrDefault(),
                        Quantity = 1
                    });
                }
                else   //ton tai thi tang so luong thoi
                {
                    cart[index].Quantity++;
                }
                SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            }
            return RedirectToPage("/Basket/View");
        }

        // xoa item trong cart

        public IActionResult OnGetDelete(int id)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            int index = Exists(cart, id);
            cart.RemoveAt(index);
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        // update quantity trong session
        public IActionResult OnPostUpdate(int[] quantities)
        {
            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            for (var i = 0; i < cart.Count; i++)
            {
                cart[i].Quantity = quantities[i];
            }
            SessionHelper.SetObjectAsJson(HttpContext.Session, "cart", cart);
            return RedirectToPage("/Basket/View");
        }

        //kiem tra id san pham da ton tai trong cart chua
        //neu ton tai thi tra ve id
        //neu khong thi tra ve -1

        private int Exists(List<Item> cart, int id)
        {
            for (var i = 0; i < cart.Count; i++)
            {
                if (cart[i].Product.ProductId == id)
                {
                    return i;
                }
            }
            return -1;
        }


        //thanhtoan
        public IActionResult OnPostThanhToan()
        {

            cart = SessionHelper.GetObjectFromJson<List<Item>>(HttpContext.Session, "cart");
            if (HttpContext.Session.GetString("username") == null)
            {
                message = "Ban chua dang nhap";
            }
            else
            {
                _service1.AddOrder(HttpContext.Session.GetString("username"), Order, cart, OrderDetail);

                //xoa session
                HttpContext.Session.Remove("cart");


            }

                return Page();
            
        }

    }
}

CleanArch_Project/RazorSample/Pages/Basket/View.cshtml
@page
@model Web.Pages.Basket.ViewModel
@{
    Layout = "../Shared/_Layout.cshtml";
}

@section icon{
    <img src="/../images/logo1.png">
}
@section slcart{

    @if (Model.cart == null)
    {
        <i>0 </i>
    }
    else
    {
        var soluong = 0;
        @foreach (var item in Model.cart)
        {
            soluong++;

        }
        <i>@soluong </i>

    }
}
@section headers{


    @if (@HttpContext.Session.GetString("username") != null)
    {

        <li>
            Hello <a asp-page="/users/details" asp-route-id="@HttpContext.Session.GetString("userid")">@HttpContext.Session.GetString("username")</a>
        </li>
        <li>
            <form method="post">
                <input asp-page="/Account/Logout/DangXuat" type="submit" value="Log out" />
            </form>
        </li>

    }
    else    //chua dang nhap
    {

        <li>
            <a asp-page="/Account/Login/DangNhap"><i class="fa fa-unlock"></i> Đăng nhập</a>
        </li>
        <li>
            <a asp-page="/Account/Register/DangKy"><i class="fa fa-share-square-o"></i> Đăng ký</a>
        </li>
    }

}

@section search{
    <form method="get" class="form-inline">
        <div class="form-group">
            <input type="text" asp-for="CurrentFilterProduct" placeholder="Keyword" class="form-control">
            <button asp-page="/Products/index" value="Search" type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
        </div>
    </form>
}
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>View</title>
</head>
<body>
    <form method="post" asp-page="/basket/view" asp-page-handler="update">
        @if (Model.cart == null)
        {

            <p>GIỎ HÀNG TRỐNG</p>
        }

        else
        {
            <div id="maincontent">
                <div class="container">
                    <div>
                        <h2 class="text-center">Chi tiết giỏ hàng</h2>


                        <div class="container">
                            <table id="cart" class="table table-hover table-condensed">
                                <thead>
                                    <tr>
                                        <th style="width:50%">Tên sản phẩm</th>
                                        <th style="width:10%">Giá</th>
                                        <th style="width:8%">Số lượng  </th>
                                        <th style="width:22%" class="text-center">Thành tiền</th>
                                        <th style="width:10%"> </th>
                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach (var item in Model.cart)
                                    {
                                        <tr>
                                            <td data-th="Product">
                                                <div class="row">
                                                    <div class="col-sm-2 hidden-xs">
                                                        <img src="#" alt="Sản phẩm " class="img-responsive" width="100">
                                                    </div>
                                                    <div class="col-sm-10">
                                                        <h4 class="nomargin">@item.Product.ProductName</h4>
                                                    </div>
                                                </div>
                                            </td>
                                            <td data-th="Price">$@item.Product.ProductPrice</td>
                                            <td><input type="number" name="quantities" value="@item.Quantity" min="1" style="width: 50px;" /></td>
                                            <td data-th="Subtotal" class="text-center">$@(item.Product.ProductPrice * item.Quantity)</td>
                                            <td>
                                                <a asp-page="/Basket/view" asp-page-handler="delete" asp-route-id="@item.Product.ProductId"><i class="fa fa-trash-o"></i></a>




                                            </td>
                                        </tr>

                                    }
                                </tbody>
                                <tfoot>
                                    <tr>
                                        <td>
                                            <a asp-page="/Products/index" class="btn btn-warning"><i class="fa fa-angle-left"></i> Tiếp tục mua hàng</a>
                                        </td>
                                        <td colspan="2" class="hidden-xs"> </td>
                                        <td class="hidden-xs text-center">
                                            <strong>Tổng tiền: $@Model.Total</strong>
                                        </td>

                                        <td>




                                            <button type="submit" value="Update" onclick="window.location.reload();" class="btn btn-warning"><i class="fa fa-angle-left"></i>Update </button>
                                        </td>
                                        <td>

                                            <button asp-page-handler="thanhtoan" asp-page="/Basket/View" type="submit" class="btn btn-success btn-block">
                                                Thanh toán <i class="fa fa-angle-right"></i>
                                            </button>

                                        </td>

                                    </tr>
                                </tfoot>
                            </table>

                            <p style="color:red">@Model.message</p>
                        </div>
                    </div>
                </div>
            </div>
        }

    </form>
    <script src="~/js/slick.min.js"></script>
</body>
</html>