CleanArch_Project/RazorSample/Pages/Account/Info/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;
using ApplicationCore.Services;
using ApplicationCore.DTOs;
using Web.Services;
using Web.ViewModels;
using Microsoft.AspNetCore.Http;

namespace Web.Pages.Account.Info
{
    public class DetailsModel : PageModel
    {
        private readonly UserVmService _service;
        [BindProperty(SupportsGet = true)]
        public string CurrentFilterProduct { get; set; }

        public DetailsModel(UserVmService service)
        {
            _service = service;
        }

        public UserDto User { get; set; }


        public UserVm userVm { get; set; }
        public IActionResult OnGet(int id)
        {

            //neu da dang nhap
            if(HttpContext.Session.GetString("username") != null)
            {

              
                    userVm = _service.GetUserViewModel(id);
              
                    
                
               
                return Page();
            }
            else
            {
                return RedirectToPage("/Index");
            }


            
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ApplicationCore.Entities;
using Infrastructure.Persistence;
using ApplicationCore.Services;
using Web.Services;

namespace Web.Pages.Admin.Admin_pages.Ad_products
{
    public class CreateModel : PageModel
    {
        
        private readonly ProductService _service;
        public CreateModel(ProductService service)
        {
            _service = service;

        }


        public IActionResult OnGet()
        {
            var providerid = _service.GetProvider();
          
            ViewData["ProductProviderId"] = new SelectList(providerid);
            return Page();
        }

        [BindProperty]
        public Product Product { get; set; }
        [BindProperty(SupportsGet = true)]
        public string message { get; set; }
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPost()
        {
            
            if (!ModelState.IsValid)
            {
                var providerid = _service.GetProvider();

                ViewData["ProductProviderId"] = new SelectList(providerid);

                return Page();
            }

            if(_service.tontaiProductname(Product))
            {
                _service.themsp(Product);
                return RedirectToPage("/Admin/Admin_pages/Ad_products/Index");
            }
            else
            {
                message = "Ten san pham da ton tai";

                var providerid = _service.GetProvider();

                ViewData["ProductProviderId"] = new SelectList(providerid);

                return Page();
            }                  
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_products
{
    public class DeleteModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public DeleteModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Product Product { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product
                .Include(p => p.ProductProvider).FirstOrDefaultAsync(m => m.ProductId == id);

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product.FindAsync(id);

            if (Product != null)
            {
                _context.Product.Remove(Product);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_products
{
    public class DetailsModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public DetailsModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        public Product Product { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product
                .Include(p => p.ProductProvider).FirstOrDefaultAsync(m => m.ProductId == id);

            if (Product == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_products
{
    public class EditModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public EditModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Product Product { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Product = await _context.Product
                .Include(p => p.ProductProvider).FirstOrDefaultAsync(m => m.ProductId == id);

            if (Product == null)
            {
                return NotFound();
            }
           ViewData["ProductProviderId"] = new SelectList(_context.Provider, "ProviderId", "ProviderId");
            return Page();
        }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(Product).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!ProductExists(Product.ProductId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool ProductExists(int id)
        {
            return _context.Product.Any(e => e.ProductId == id);
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;
using Microsoft.AspNetCore.Mvc.Rendering;
using Web.Services;
using Web.ViewModels;
using Microsoft.AspNetCore.Http;
using ApplicationCore.DTOs;

namespace Web.Pages.Admin.Admin_pages.Ad_products
{
    public class IndexModel : PageModel
    {
        private readonly ProductListVmService _ProductService;
        public IndexModel(ProductListVmService ProductService)
        {
            _ProductService = ProductService;
        }

        [BindProperty(SupportsGet = true)]
        public string CurrentFilterProduct { get; set; }

        public string CurrentSort { get; set; }

        [BindProperty(SupportsGet = true)]
        public string typename { get; set; }

        [BindProperty(SupportsGet = true)]
        public string sort { get; set; }

        public ProviderDto Provider { get; set; }

        public ProductListVm ProductIndexVM { get; set; }

        public void Onpost()
        {

        }

        public IActionResult OnGet(string sortoder, int pageIndex = 1)
        {           
            string? item = HttpContext.Session.GetString("userid");
            if (item != null)
            {
                if (sort == "giam")
                {

                    ProductIndexVM = _ProductService.GetProductPriceDecrease(CurrentFilterProduct, typename, pageIndex);

                }
                else
                {
                    ProductIndexVM = _ProductService.GetProductIndexViewModel(CurrentFilterProduct, typename, pageIndex);                    
                }
                
                return Page();              
            }
            else
            {
               
                return RedirectToPage("/Admin/Admin_login");
            
            }
        }
        public IActionResult OnPostSignout()
        {
            HttpContext.Session.Remove("username");
            HttpContext.Session.Clear();
            return RedirectToPage("/Admin/Admin_login");
        }




    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_users/Create.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_users
{
    public class CreateModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public CreateModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        public IActionResult OnGet()
        {
        ViewData["UserCustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId");
        ViewData["UserPermissionId"] = new SelectList(_context.Set<Permission>(), "PermissionId", "PermissionId");
            return Page();
        }

        [BindProperty]
        public User User { get; set; }

        // To protect from overposting attacks, please enable the specific properties you want to bind to, for
        // more details see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.User.Add(User);
            await _context.SaveChangesAsync();

            return RedirectToPage("./Index");
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_users/Delete.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_users
{
    public class DeleteModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public DeleteModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        [BindProperty]
        public User User { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.User
                .Include(u => u.UserCustomer)
                .Include(u => u.UserPermission).FirstOrDefaultAsync(m => m.UserId == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.User.FindAsync(id);

            if (User != null)
            {
                _context.User.Remove(User);
                await _context.SaveChangesAsync();
            }

            return RedirectToPage("./Index");
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_users/Details.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_users
{
    public class DetailsModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public DetailsModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        public User User { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.User
                .Include(u => u.UserCustomer)
                .Include(u => u.UserPermission).FirstOrDefaultAsync(m => m.UserId == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_users/Edit.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ApplicationCore.Entities;
using Infrastructure.Persistence;

namespace Web.Pages.Admin.Admin_pages.Ad_users
{
    public class EditModel : PageModel
    {
        private readonly Infrastructure.Persistence.ProductContext _context;

        public EditModel(Infrastructure.Persistence.ProductContext context)
        {
            _context = context;
        }

        [BindProperty]
        public User User { get; set; }

        public async Task<IActionResult> OnGetAsync(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            User = await _context.User
                .Include(u => u.UserCustomer)
                .Include(u => u.UserPermission).FirstOrDefaultAsync(m => m.UserId == id);

            if (User == null)
            {
                return NotFound();
            }
           ViewData["UserCustomerId"] = new SelectList(_context.Customer, "CustomerId", "CustomerId");
           ViewData["UserPermissionId"] = new SelectList(_context.Set<Permission>(), "PermissionId", "PermissionId");
            return Page();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            _context.Attach(User).State = EntityState.Modified;

            try
            {
                await _context.SaveChangesAsync();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!UserExists(User.UserId))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return RedirectToPage("./Index");
        }

        private bool UserExists(int id)
        {
            return _context.User.Any(e => e.UserId == id);
        }
    }
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Create.cshtml
@page
@model Web.Pages.Admin.Admin_pages.Ad_products.CreateModel
@{
    ViewData["Title"] = "Create";
    Layout = "~/Pages/Shared/_LayoutAdmin_pages.cshtml";
}


@section Navigation
{
    <div class="breadcrumb">
        <span><a asp-page="./Admin_index">Home</a></span>
        <span> / </span>
        <span><a asp-page="./Ad_product/Index">Products</a></span>
        <span> / </span>
        <span> Create </span>
    </div>
}
<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product.ProductName" class="control-label"></label>
                <input asp-for="Product.ProductName" class="form-control" />
                <span class="text-danger" style="color:red">@Model.message</span>
                <span asp-validation-for="Product.ProductName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductTypeName" class="control-label"></label>
                <input asp-for="Product.ProductTypeName" class="form-control" />
                <span asp-validation-for="Product.ProductTypeName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductPrice" class="control-label"></label>
                <input asp-for="Product.ProductPrice" class="form-control" />
                <span asp-validation-for="Product.ProductPrice" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductQuantity" class="control-label"></label>
                <input asp-for="Product.ProductQuantity" class="form-control" />
                <span asp-validation-for="Product.ProductQuantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductImage" class="control-label"></label>
                <input asp-for="Product.ProductImage" class="form-control" />
                <span asp-validation-for="Product.ProductImage" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductDescription" class="control-label"></label>
                <input asp-for="Product.ProductDescription" class="form-control" />
                <span asp-validation-for="Product.ProductDescription" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product.ProductProviderId" class="control-label"></label>
                <select asp-for="Product.ProductProviderId" class="form-control" asp-items="ViewBag.ProductProviderId"></select>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Delete.cshtml
@page
@model Web.Pages.Admin.Admin_pages.Ad_products.DeleteModel

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Pages/Shared/_LayoutAdmin_pages.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductTypeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductTypeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductQuantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductQuantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductImage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductImage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductProvider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductProvider.ProviderId)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Product.ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-page="./Index">Back to List</a>
    </form>
</div>

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Details.cshtml
@page
@model Web.Pages.Admin.Admin_pages.Ad_products.DetailsModel

@{
    ViewData["Title"] = "Details";
    Layout = "~/Pages/Shared/_LayoutAdmin_pages.cshtml";
}

<h1>Details</h1>

<div>
    <h4>Product</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductTypeName)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductTypeName)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductPrice)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductPrice)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductQuantity)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductQuantity)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductImage)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductImage)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductDescription)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductDescription)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Product.ProductProvider)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductProvider.ProviderId)
        </dd>
    </dl>
</div>
<div>
    <a asp-page="./Edit" asp-route-id="@Model.Product.ProductId">Edit</a> |
    <a asp-page="./Index">Back to List</a>
</div>

CleanArch_Project/RazorSample/Pages/Admin/Admin_pages/Ad_products/Index.cshtml
@page
@model Web.Pages.Admin.Admin_pages.Ad_products.IndexModel

@{
    ViewData["Title"] = "Index";
    Layout = "~/Pages/Shared/_LayoutAdmin_pages.cshtml";
}
@section right_header
{
    <div class="nav-right">
        <img src="~/image/icon/user-icon.svg" />
        <div class="ten-admin"><a>Hello - @HttpContext.Session.GetString("username")!</a></div>
        <form asp-page-handler="Signout" method="post">

            <input type="submit" style="font-size: 15px;margin:17px 8px 0 8px" value="Sign Out"/>

        </form>
    </div>
}
@section Navigation
{
    <div class="breadcrumb">
        <span><a asp-page="./Admin_index">Home</a></span>
        <span> / </span>
        <span>Products</span>
    </div>
}
<div class="section">
    <div class="them_sp" style="float:left"><a asp-page="./Create">Thêm Sản Phẩm</a></div>

    <form method="get">
        <p>
            <!-- sort by genres -->
            <select asp-for="typename" asp-items="Model.ProductIndexVM.Genres">
                <option value="">All</option>
            </select>
            <!-- sort by provider -->
            <select asp-for="typename" asp-items="Model.ProductIndexVM.Provider">
                <option value="">All</option>
            </select>
            <!--> search </!-->
            Find by name: <input type="text" asp-for="CurrentFilterProduct" />
            <input type="submit" />
            <!-- Sort by price decrease -->
            <a asp-page="./index" asp-route-sort="giam">Price Decrease</a>
        </p>
    </form>

    <table id="table-sp">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.ProductIndexVM.Products[0].ProductName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductIndexVM.Products[0].ProductTypeName)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductIndexVM.Products[0].ProductPrice)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductIndexVM.Products[0].ProductQuantity)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductIndexVM.Products[0].ProductImage)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductIndexVM.Products[0].ProductDescription)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.ProductIndexVM.Products[0].ProductProvider)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model.ProductIndexVM.Products)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductTypeName)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductPrice)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductQuantity)
                    </td>
                    <td>
                        <img width="100" src="~/images/@Html.DisplayFor(modelItem => item.ProductImage)"/> 
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductDescription)
                    </td>                    
                    <td>
                        @Html.DisplayFor(modelItem => item.ProductProviderId)
                    </td>
                    <td>
                        <button class="sua_sp"><a asp-page="./Edit" asp-route-id="@item.ProductId">Edit</a></button>
                        <button class="xoa_sp"><a asp-page="./Delete" asp-route-id="@item.ProductId">Delete</a></button>
                    </td>
                </tr>
            }
        </tbody>

    </table>

    <div>
        <a asp-page="./Index">Back to List</a>
    </div>
    <div style="float:right">        
        @for (int i = 1; i <= @Model.ProductIndexVM.Products.TotalPages; i++)
        {
            <div style="width:30px;float:left;@(i == Model.ProductIndexVM.Products.PageIndex ? "pointer-events:none" : "")">
                <table style="border-style:solid">
                    <!--<tbody> -->
                    <thead>
                        <tr>
                            <th>
                                <a style="position:center"
                                   asp-page="./Index"
                                   asp-route-currentFilterproduct="@Model.CurrentFilterProduct"
                                   asp-route-typename="@Model.typename"
                                   asp-route-sort="@Model.sort"
                                   asp-route-pageIndex="@i"
                                   class="page-item @(i == Model.ProductIndexVM.Products.PageIndex ? "active" : "")">
                                    @i
                                </a>
                            </th>
                        </tr>
                    </thead>
                    <!--</tbody> -->
                </table>
            </div>
        }
    </div>

</div>